### ISSUE TITLE
Considering using a license compatible with Apache v2?

### ISSUE THREAD

**Issue by amyblais** [muristan/aqbanking2mattermost#1]
Hi @muristan,

We would like to promote this integration by adding it to our [list of Apps and Integrations](https://about.mattermost.com/community-applications/) and by tweeting about it, but GNU is not one of the licenses compatible with Apache v2 that we support. Would you consider adding another license, such as MIT or any other listed [here](https://www.apache.org/legal/resolved.html#category-a)?

Let me know if you have any questions!

**Comment by muristan** [comment]
Added Apache v2 license.
